name: DevOps cart CI

on:
  push:
   branches:
     - main
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_CURRENCY_SYMBOL: ${{vars.NEXT_PUBLIC_CURRENCY_SYMBOL}}

    steps:
      - name: Checkout repository on the runner
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            --username "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Build and push Docker image
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          docker build -t devops-cart-app .
          docker tag devops-cart-app ${{ secrets.DOCKERHUB_USERNAME }}/devops-cart-app:$BRANCH_NAME
          docker tag flask-message-app ${{ secrets.DOCKERHUB_USERNAME }}/flask-message-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-cart-app:$BRANCH_NAME
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-message-app:latest

     